[build]
  command = "pip install -r requirements.txt"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[dev]
  command = "python app.py"
  port = 5000

[context.production]
  environment = { ENABLE_MODEL_INFERENCE = "0" }
